# \u5F53\u524D\u670D\u52A1\u7684\u540D\u79F0
spring:
  application:
    name: gateway-client-consumer
  cloud:
    gateway:
      routes:
        - id: cxy35_route
          uri: http://httpbin.org # \u8FD9\u662F\u4E00\u4E2A\u6D4B\u8BD5\u7684\u5730\u5740
          predicates:
            - Path=/get
        - id: cxy35_route2
          uri: http://httpbin.org # \u8FD9\u662F\u4E00\u4E2A\u6D4B\u8BD5\u7684\u5730\u5740
          predicates:
            - After=2021-01-01T01:01:01+08:00[Asia/Shanghai]
            - Method=GET
            - Query=name,java.*
        - id: cxy35_route3
          uri: lb://gateway-client-provider
          filters:
            - AddRequestParameter=name,cxy35
          predicates:
            - Method=GET
      discovery:
        locator:
          enabled: true # \u5f00\u542f\u4ece\u6ce8\u518c\u4e2d\u5fc3\u52a8\u6001\u521b\u5efa\u8def\u7531\u7684\u529f\u80fd
          # lower-case-service-id: true # \u4f7f\u7528\u5c0f\u5199\u670d\u52a1\u540d\uff0c\u9ed8\u8ba4\u662f\u5927\u5199
# \u5F53\u524D\u670D\u52A1\u7684\u7AEF\u53E3
server:
  port: 7002

# \u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug